### ISSUE TITLE
Uma linha de transmissão é

### ISSUE THREAD

**Issue by joaoarquimedes** [vmartins/simulado-coer-anatel#1]
Na pertgunta: Uma linha de transmissão é.
A resposta correta não seria "um fio que acopla a energia do transmissor ao espaço"?

**Comment by vmartins** [comment]
As perguntas e respostas foram retirados do site da [Anatel](https://www.gov.br/anatel/pt-br/regulado/outorga/radioamador-e-radio-cidadao/habilitacao-do-radioamador). Veja no arquivo [Técnica e Ética Operacional, de 20/12/2008](https://sistemas.anatel.gov.br/anexar-api/publico/portal-publicar/documentos?numeroPublicacao=230615) que a resposta da pergunta 61 é a letra **D**:

> um cabo que leva a energia do transmissor para a antena;

De acordo com o [Guia Técnico da "Estação de Radioamador no Grupo Escoteiro"](https://www.escoteirossp.org.br/down/guia-tecnico-da-estacao-de-radioamador-no-grupo-escoteiro-ed-2018-final-pdf/):

> **Linha de transmissão** – É o cabo que leva o sinal de rádio desde o transmissor até a antena, ou no sentido inverso, que leva o sinal da antena até o receptor. Pode ser um cabo coaxial, uma fita de condutores paralelos ou até um par de fios torcidos. Com algum conhecimento e um pouco de matemática é fácil aperfeiçoar a linha de transmissão;
